# Generated by Django 4.2.29 on 2026-03-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'metrics',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SensorVariant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField()),
                ('variant_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sensor_variants',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('precision', models.IntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.metric')),
            ],
            options={
                'db_table': 'units',
                'ordering': ['id'],
            },
        ),
    ]
