# Generated by Django 4.2.29 on 2026-03-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'metrics',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetricUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metric')),
            ],
            options={
                'db_table': 'metric_units',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('precision', models.IntegerField()),
                ('metrics', models.ManyToManyField(related_name='units', through='api.MetricUnit', to='api.metric')),
            ],
            options={
                'db_table': 'units',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField()),
                ('variant_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sensor_types',
                'ordering': ['id'],
                'unique_together': {('type_id', 'variant_id')},
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.sensortype')),
            ],
            options={
                'db_table': 'sensors',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='metricunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='metricunit',
            unique_together={('metric', 'unit')},
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('measured_at', models.DateTimeField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.metric')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.sensor')),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['measured_at'],
                'indexes': [models.Index(fields=['sensor', 'metric', 'measured_at'], name='measurement_sensor__888def_idx'), models.Index(fields=['measured_at'], name='measurement_measure_a57da4_idx')],
            },
        ),
    ]
