# Generated by Django 4.2.29 on 2026-03-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'metrics',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('precision', models.IntegerField()),
            ],
            options={
                'db_table': 'units',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetricUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metric')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit')),
            ],
            options={
                'db_table': 'metric_units',
                'unique_together': {('metric', 'unit')},
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(is_primary=True),
                        fields=['metric'],
                        name='unique_primary_unit_per_metric'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField()),
                ('variant_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sensor_types',
                'ordering': ['id'],
                'unique_together': {('type_id', 'variant_id')},
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sensor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.sensortype')),
            ],
            options={
                'db_table': 'sensors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('measured_at', models.DateTimeField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.metric')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.sensor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.unit')),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['measured_at'],
                'unique_together': {('measured_at', 'metric', 'unit')},
                'indexes': [
                    models.Index(fields=['sensor', 'metric', 'measured_at'], name='measurement_sensor__888def_idx'),
                    models.Index(fields=['measured_at'], name='measurement_measure_a57da4_idx'),
                ],
            },
        ),
    ]
