# Generated by Django 4.2.29 on 2026-03-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sensor_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.sensorvariant')),
            ],
            options={
                'db_table': 'sensors',
                'ordering': ['id'],
            },
        ),
    ]
