# Generated by Django 4.2.29 on 2026-03-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('measured_at', models.DateTimeField()),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.metric')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.sensor')),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['measured_at'],
                'indexes': [models.Index(fields=['sensor', 'metric', 'measured_at'], name='measurement_sensor__888def_idx'), models.Index(fields=['measured_at'], name='measurement_measure_a57da4_idx')],
            },
        ),
    ]
