# Generated by Django 4.2.29 on 2026-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sensor_name_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='metricunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('metric',), name='unique_primary_unit_per_metric'),
        ),
    ]
